-- \i /home/globik/sex_for_many/sql/card_number.sql
drop table if exists card_number;
create table if not exists card_number(id int generated by default as identity,
bname varchar(16) UNIQUE NOT NULL references buser(bname),
cn int not null -- a card number of a bank
);
