-- \i /home/globik/sex_for_many/sql/model_doc.sql
drop table if exists model_doc;
create table if not exists model_doc(id int generated by default as identity,
pass text not null, -- passport src
foto text not null, -- foto src
stat int not null default 0 -- 0 - ne odobreno, 1 - odobreno
);
