-- \i /home/globi/sex_for_many/sql/sean.sql
-- \i /root/sex_for_many/sql/sean.sql
drop table if exists sean;
CREATE TABLE IF NOT EXISTS sean(
id int generated by default as identity,
sname varchar(16) not null references buser(bname),
typ int not null, -- type of stream 0 = all, 1 = privat
crat TIMESTAMP NOT NULL default now()::timestamp, -- beginning of a stream
endat TIMESTAMP NOT NULL default now()::timestamp -- ending of a stream
);
-- insert into sean(sname, typ) values('Globi',0) returning id;
