-- \i /home/globik/sex_for_many/sql/token_payout.sql
drop table if exists token_payout;
create table if not exists token_payout(
id int generated by default as identity,
tom varchar(16) not null references buser(bname),
suma numeric not null, -- bitcoins
cr_at TIMESTAMP NOT NULL default now()::timestamp
);

create or replace function on_token_payout(tom varchar(16),suma numeric) returns void
language plpgsql as $$
begin
insert into token_payout(tom,suma) values(on_token_payout.tom, on_token_payout.suma);
update buser set items=0 where bname=on_token_payout.tom;	
end;
$$;
-- select on_token_payout('Globi','100'::numeric);
