-- \i /home/globi/sex_for_many/sql/token_payout.sql
drop table if exists token_payout;
create table if not exists token_payout(
id int generated by default as identity,
pid int not null, -- id of a user
tom varchar(16) not null references buser(bname),
suma numeric not null, -- bitcoins
cr_at TIMESTAMP NOT NULL default now()::timestamp
);
drop function if exists on_token_payout(varchar,numeric);
create or replace function on_token_payout(tom varchar(16),suma numeric, pid int) returns void
language plpgsql as $$
begin
insert into token_payout(tom,suma,pid) values(on_token_payout.tom, on_token_payout.suma,on_token_payout.pid);
update buser set items=0,promo=0 where buser.id=on_token_payout.pid;	
end;
$$;
-- select on_token_payout('Globi','100'::numeric,1,0)
