-- \i /home/globik/sex_for_many/sql/video.sql
drop table if exists video;
CREATE TABLE IF NOT EXISTS video(
id int generated by default as identity,
nick varchar(20) not null,
src varchar(100) not null,
cr_at timestamp not null default now());
grant all privileges on table video to suka;
